catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('allbooks/', views.LoanedBooksListView.as_view(), name='all-borrowed'),

    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
]

urlpatterns += [   
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]

urlpatterns += [  
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
]

urlpatterns += [  
    path('book/create/', views.BookCreate.as_view(), name='book_create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book_update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book_delete'),
]

urlpatterns += [   
    path('farms/', views.FarmListView.as_view(), name='farms'),
    path('farm/<int:pk>', views.FarmDetailView.as_view(), name='farm-detail'),

    path('farm/create/', views.FarmCreate.as_view(), name='farm_create'),
    path('farm/<int:pk>/update/', views.FarmUpdate.as_view(), name='farm_update'),
    path('farm/<int:pk>/delete/', views.FarmDelete.as_view(), name='farm_delete'),

    #path('farms/', views.FarmListView.as_view(), name='farms'),
    #path('farm/<int:pk>', views.FarmDetailView.as_view(), name='farm-detail'),
]

saharafarmers/urls.py
# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView

# Use include() to add paths from the catalog application 
from django.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('exportation/', include('exportation.urls')),
    path('farmersforum/', include('farmersforum.urls')),
    path('rentals/', include('rentals.urls')),

    path('', RedirectView.as_view(url='catalog/')),
    path('', RedirectView.as_view(url='exportation/')),
    path('', RedirectView.as_view(url='farmersforum/')),
    path('', RedirectView.as_view(url='rentals/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from datetime import date
from django.db import models
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
import uuid # Required for unique book instances
from django.contrib.auth.models import User


#from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.

class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')
    
    def __str__(self):
        """String for representing the Model object."""
        return self.name

class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    
    def __str__(self):
        """String for representing the Model object."""
        return self.title
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'        

class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True) 
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False    


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'


"""
SaharaFarms Models start here
"""

class Country(models.Model):
    """Model representing an African Countries."""
    country_name = models.CharField(max_length=200)
    capital = models.CharField(max_length=200, default=None, blank=True, null=True)
    country_population = models.IntegerField()

    class Meta:
        ordering = ['country_name']

    # def get_absolute_url(self):
    #     """Returns the url to access a particular country instance."""
    #     return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.country_name

class State(models.Model):
    """Model representing an African States."""
 # Foreign Key used because state can only have one country, but countries can have multiple states
    # Country as a string rather than object because it hasn't been declared yet in the file
    country = models.ForeignKey('Country', on_delete=models.SET_NULL, null=True)
    state_name = models.CharField(max_length=200)
    capital = models.CharField(max_length=200, default=None, blank=True, null=True)
    slogan = models.CharField(max_length=200, default=None, blank=True, null=True)

    class Meta:
        ordering = ['state_name']

    def display_country(self):
        """Create a string for the Country. This is required to display country in Admin."""
        return ', '.join(Country.country_name for Country in self.Country.all()[:3])
    
    display_country.short_description = 'Country'

    # def get_absolute_url(self):
    #     """Returns the url to access a particular country instance."""
    #     return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.state_name

class LocalGovt(models.Model):
    """Model representing an African local governments."""
     # Foreign Key used because Local Government can only have one state, but states can have multiple Local Governments
    # State as a string rather than object because it hasn't been declared yet in the file
    state = models.ForeignKey('State', on_delete=models.SET_NULL, null=True)
    localgovt_name = models.CharField(max_length=200)

    class Meta:
        ordering = ['localgovt_name']

    # def get_absolute_url(self):
    #     """Returns the url to access a particular country instance."""
    #     return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.localgovt_name


"""
SaharaFarms Crops Models
"""

class CropGroup(models.Model):
    """Model representing Crop Groups."""
    group_name = models.CharField(max_length=200)

    class Meta:
        ordering = ['group_name']

    def get_absolute_url(self):
        """Returns the url to access a particular crop group instance."""
        return reverse('group-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.group_name

class CropClass(models.Model):
    """Model representing Crop Class."""
    cropgroup = models.ForeignKey('CropGroup', on_delete=models.SET_NULL, null=True)
    class_name = models.CharField(max_length=200)
    
    class Meta:
        ordering = ['class_name']

    def get_absolute_url(self):
        """Returns the url to access a particular class of crops instance."""
        return reverse('class-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.class_name

class CropSubClass(models.Model):
    """Model representing a subclass of crop in a class of crop."""
    subclass_name = models.CharField(max_length=200)
    cropclass = models.ForeignKey('CropClass', on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['subclass_name']

    def get_absolute_url(self):
        """Returns the url to access a particular crop sub class instance."""
        return reverse('subclass-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.subclass_name


"""
SaharaFarms Farm Registration Model
"""

# class Client(models.Model, Importable):
#     phone = PhoneNumberField(null=False, blank=False, unique=True)


class Farm(models.Model):
    """Model representing a farm. """
    farm_name = models.CharField(max_length=500)
    localgovt = models.ForeignKey('LocalGovt', on_delete=models.SET_NULL, null=True)
    telephone1 = models.CharField(max_length=13)
    telephone2 = models.CharField(max_length=13)
    enailAddress = models.EmailField(max_length=70, blank=True, null= True, unique= True)
    description = models.TextField(max_length=1000, help_text='Enter a brief description of the farm')    
    def __str__(self):
        """String for representing the Model object."""
        return self.farm_name   
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this farm."""
        return reverse('farm-detail', args=[str(self.id)])


""" SaharaFarms Farm Online Products Store Model """

class ProduceStore(models.Model):
    """Model representing a farm. """
    #farm_name = models.CharField(max_length=500)
    farm = models.ForeignKey('Farm', on_delete=models.SET_NULL, null=True)
    cropclass = models.ForeignKey('CropClass', on_delete=models.SET_NULL, null=True)
    cropsubclass = models.ForeignKey('CropSubClass', on_delete=models.SET_NULL, null=True)
    description = models.TextField(max_length=1000, help_text='Enter a brief description of the produce')
    quantity = models.DecimalField(max_digits=16, decimal_places=2)
    rate = models.DecimalField(max_digits=10, decimal_places=2)
       
    def __str__(self):
        """String for representing the Model object."""
        return self.description
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this farm."""

catalog/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
    
class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")
    
    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        
        # Check if a date is not in the past. 
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author: {{ author.first_name }} , {{ author.last_name }}</h1>
  {{author.date_of_birth}} - {{author.date_of_death}}

  <div style="margin-left:20px;margin-top:20px">
    <h4>Books</h4>

    {% for c in book.author_set.all %}
      <hr>
      <!-- <p><strong></strong><a href="{{ book.get_absolute_url }}">{{ copy.title }}</a></strong></p> ({{copy.bookinstance.count}}) -->
      <p><strong></strong><a href="{{ book.get_absolute_url }}">{{ c.title }}</a></strong></p>
      <p>{{ c.summary }}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author List</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name }} , {{ author.last_name }}</a> ({{author.date_of_birth}} - {{author.date_of_death}}) 
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}       
{% endblock %}

catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the book: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Language:</strong> {{ book.language }}</p>  
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}       
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>
    
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Borrowed Books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})  
        {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>  {% endif %}      
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>My Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/farm_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Farm: {{ farm.farm_name }}</h1>

  <p><strong>Country:</strong> {{ farm.localgovt.state.country.country_name }}</p>
  <p><strong>State:</strong> {{ farm.localgovt.state.state_name }}</p>
  <p><strong>Local Government/Province:</strong> {{ farm.localgovt }}</p> 
  <p><strong>Telephone 1 & 2:</strong> {{ farm.telephone1 }} / {{ farm.telephone2 }}</p>  
  <p><strong>Email Address:</strong> {{ farm.enailAddress }}</p>  
  <p><strong>Farm Description:</strong> {{ farm.description }}</p>

  <p><strong>Products:</strong> <a href="">{{ farm.farm_name }}</a></p>  <!--author detail link not yet defined ProduceStore. -->

   <div style="margin-left:20px;margin-top:20px">
    <h4>Farm Produce</h4>
    <!-- <hr> -->

    
    <table class="table-bordered">
        <tr>
            <th>Crop</th>
            <th>Crop Type</th>
            <th>Description</th>
            <th>Quantity</th>
            <th>Rate</th>
        </tr>             
    {% for product in farm.producestore_set.all %}
        <tr>
            <td>{{ product.cropclass.class_name }}</td>
            <td>{{ product.cropsubclass.subclass_name }}</td>
            <td>{{ product.description }}</td>
            <td>{{ product.quantity }}</td>
            <td>{{ product.rate }}</td>
        </tr>  
      <!-- <p class="text-muted"><strong>Id:</strong> {{ product.id }}</p> -->
    {% endfor %}
    </table>
  </div>
  <br>
{% endblock %}

catalog/templates/catalog/farm_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/farm_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Farm List</h1>
  {% if farm_list %}
  <ul>
    {% for farm in farm_list %}
      <li>
        <a href="{{ farm.get_absolute_url }}">{{ farm.farm_name }}</a> ({{farm.farm_name}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>No farm found in the database.</p>
  {% endif %}       
{% endblock %}